# Generated by Django 5.2.7 on 2025-10-22 ation):
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('show_in_pos', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='combos', to='canteen.product')),
            ],
        ),
    ]
