# Generated by Django 5.2.7 on 2026-03-14 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0002_combo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="canteen_ord_created_c9f33d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["is_paid", "cancelled", "created_at"],
                name="canteen_ord_is_paid_437c6f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["cashier", "created_at"], name="canteen_ord_cashier_08683c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["in_stock", "name"], name="canteen_pro_in_stoc_b72cb4_idx"
            ),
        ),
    ]
